services:
  postgres:
    image: postgres:15
    networks:
      - airflow-oracle-network
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      retries: 5

  airflow-webserver:
    build: .
    networks:
      - airflow-oracle-network
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: ${AIRFLOW__CORE__EXECUTOR}
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: ${AIRFLOW__CORE__SQL_ALCHEMY_CONN}
      AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW__CORE__FERNET_KEY}
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - /Users/dollayapiumsuwan/Documents/01_DataAtDawn/PEOPLE-ANALYTICS/hr-data-warehouse-oracle/data:/data
    ports:
      - "8080:8080"
    command: >
      bash -c "airflow db init &&
        airflow users create --username admin --password admin --firstname Admin --lastname Admin --role Admin --email admin@example.com &&
        airflow webserver"

  airflow-scheduler:
    build: .
    networks:
      - airflow-oracle-network
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: ${AIRFLOW__CORE__EXECUTOR}
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: ${AIRFLOW__CORE__SQL_ALCHEMY_CONN}
      AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW__CORE__FERNET_KEY}
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - /Users/dollayapiumsuwan/Documents/01_DataAtDawn/PEOPLE-ANALYTICS/hr-data-warehouse-oracle/data:/data
    command: >
      bash -c "airflow db init && airflow scheduler"

networks:
  airflow-oracle-network:
    external: true